---
git:
  depth: 1
sudo: false

cache:
  directories:
  - node_modules

language: node_js
node_js: node

before_deploy: npm run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github-token: $GITHUB_TOKEN
  on:
    branch: master
